name: driver_monitoring
description: "A real-time driver monitoring application."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.8.1 
  shared_preferences: ^2.2.1 
  drift: ^2.26.0  
  sqlite3_flutter_libs: ^0.5.31  
  path: any
  path_provider: ^2.1.2 
  fl_chart: ^0.70.2 
  syncfusion_flutter_charts: ^28.2.11
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  collection: any
  logger: any
  intl: any
  camera: ^0.11.1
  camera_android: ^0.10.10+1  #fărp el nu lucrează landmarcurile pe imagine
  permission_handler: any
  flutter_foreground_task: ^8.17.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_commons: ^0.9.0
  flutter_ringtone_player: ^4.0.0+4
  wakelock_plus: ^1.2.10
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  drift_dev: ^2.21.0

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/gifs/
    - assets/images/
    - assets/sounds/

  uses-material-design: true

